/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { FloatingButtonConfig } from "./interfaces/FloatingButtonConfig";
export namespace Components {
    interface PskConversation {
        "configPath": string;
    }
    interface PskFloatingButtonGroup {
        "backdrop": boolean;
        "buttons": FloatingButtonConfig[];
        "opened": boolean;
    }
    interface PskFragment {
    }
}
declare global {
    interface HTMLPskConversationElement extends Components.PskConversation, HTMLStencilElement {
    }
    var HTMLPskConversationElement: {
        prototype: HTMLPskConversationElement;
        new (): HTMLPskConversationElement;
    };
    interface HTMLPskFloatingButtonGroupElement extends Components.PskFloatingButtonGroup, HTMLStencilElement {
    }
    var HTMLPskFloatingButtonGroupElement: {
        prototype: HTMLPskFloatingButtonGroupElement;
        new (): HTMLPskFloatingButtonGroupElement;
    };
    interface HTMLPskFragmentElement extends Components.PskFragment, HTMLStencilElement {
    }
    var HTMLPskFragmentElement: {
        prototype: HTMLPskFragmentElement;
        new (): HTMLPskFragmentElement;
    };
    interface HTMLElementTagNameMap {
        "psk-conversation": HTMLPskConversationElement;
        "psk-floating-button-group": HTMLPskFloatingButtonGroupElement;
        "psk-fragment": HTMLPskFragmentElement;
    }
}
declare namespace LocalJSX {
    interface PskConversation {
        "configPath"?: string;
    }
    interface PskFloatingButtonGroup {
        "backdrop"?: boolean;
        "buttons"?: FloatingButtonConfig[];
        "opened"?: boolean;
    }
    interface PskFragment {
    }
    interface IntrinsicElements {
        "psk-conversation": PskConversation;
        "psk-floating-button-group": PskFloatingButtonGroup;
        "psk-fragment": PskFragment;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "psk-conversation": LocalJSX.PskConversation & JSXBase.HTMLAttributes<HTMLPskConversationElement>;
            "psk-floating-button-group": LocalJSX.PskFloatingButtonGroup & JSXBase.HTMLAttributes<HTMLPskFloatingButtonGroupElement>;
            "psk-fragment": LocalJSX.PskFragment & JSXBase.HTMLAttributes<HTMLPskFragmentElement>;
        }
    }
}
